project:
  type: website
  output-dir: docs

website:
  title: "Samantha Sellinger"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - education.qmd
      - experience.qmd
      - moreaboutme.qmd

format:
  html:
    theme: 
      light: lumen
      dark: solar
    css: styles.css
    toc: false

editor: visual

