---
title: "Experience"
format: html
editor: visual
---

#### Statistics Canada, Part-time Student (September 2024 - Present)

-   Translation of SAS production files to Python.

-   Member of the StatCan R/Python Users Group (RPUG) management team.

#### Statistics Canada, Co-op Student (May 2024 - August 2024)

-   Translation of SAS production program to Python.

-   Development of PowerBi Dashboards used to facilitate the data quality assurance processes.

-   Creation of Python tests to assist in data analysis of production tasks.

-   Member of the StatCan R/Python Users Group (RPUG) management team and committee.

#### Global Affairs Canada, Junior Data Science Analyst (May 2023 - April 2024)

-   Performed data quality assurance in the production process of the Statistical Report on International Assistance.

-   Aided in the publication of the 2022-2023 Statistical Report on International Assistance.

-   Created and maintained a PowerBi Dashboard that tracks divisional activities in relation to ad hoc reporting.

-   Assisted with ad hoc reporting.
